sign-commit = false
sign-tag = false
push = true
publish = false 
tag-name = "v{{version}}"
tag-message = "Release {{version}}"
pre-release-commit-message = "chore: bump version {{prev_version}} → {{version}}"
