[package]
name = "calc"
version = "0.1.1"
edition = "2024"
authors = ["Onismond Yao Duame onismondyao@gmail.com"]
license = "MIT"

description = "A simple CLI calculator supporting sum, sub, mul, div"
homepage = "https://github.com/onismond/calc"
repository = "https://github.com/onismond/calc"
readme = "README.md"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
