name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # ---------------- Linux builds ----------------
      - name: Install packaging tools (from binaries)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo install cargo-generate-rpm
          pip install --upgrade cloudsmith-cli

      - name: Build .deb package
        if: matrix.os == 'ubuntu-latest'
        run: cargo deb

      - name: Generate RPM package
        if: matrix.os == 'ubuntu-latest'
        run: cargo generate-rpm

      - name: Upload .deb to Cloudsmith
        if: matrix.os == 'ubuntu-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push deb onismond/calc/ubuntu/jammy target/debian/*.deb
        continue-on-error: true

      - name: Upload .rpm to Cloudsmith
        if: matrix.os == 'ubuntu-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push rpm onismond/calc/el/8 target/generate-rpm/*.rpm
        continue-on-error: true

      # ---------------- Windows builds ----------------
      - name: Install Cloudsmith CLI
        if: matrix.os == 'windows-latest'
        timeout-minutes: 10
        run: |
          pip install --upgrade cloudsmith-cli

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        timeout-minutes: 10
        run: cargo build --release

      - name: Upload Windows exe to Cloudsmith
        if: matrix.os == 'windows-latest'
        timeout-minutes: 10
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw onismond/calc target/release/calc.exe --version ${{ github.ref_name }}
        continue-on-error: true

      # ---------------- macOS builds ----------------
      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: cargo build --release

      - name: Install Cloudsmith CLI (macOS)
        if: matrix.os == 'macos-latest'
        run: pip install --upgrade cloudsmith-cli

      - name: Upload macOS binary to Cloudsmith
        if: matrix.os == 'macos-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw onismond/calc target/release/calc --version ${{ github.ref_name }}
        continue-on-error: true
