name: Release

on:
  push:
    tags:
      - "v*.*.*" 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # ---------------- Linux builds ----------------
      - name: Install packaging tools
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo install cargo-rpm
          pip install --upgrade cloudsmith-cli

      - name: Build .deb
        if: matrix.os == 'ubuntu-latest'
        run: cargo deb

      - name: Build .rpm
        if: matrix.os == 'ubuntu-latest'
        run: cargo rpm build

      - name: Upload .deb to Cloudsmith
        if: matrix.os == 'ubuntu-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push deb onismond/calc/debian/any-version target/debian/*.deb

      - name: Upload .rpm to Cloudsmith
        if: matrix.os == 'ubuntu-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push rpm onismond/calc/el/any-version target/release/rpmbuild/RPMS/x86_64/*.rpm

      # ---------------- Windows builds ----------------
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo build --release

      - name: Upload Windows exe to Cloudsmith
        if: matrix.os == 'windows-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw onismond/calc/windows/any-version target/release/calc.exe

      # ---------------- macOS builds ----------------
      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: cargo build --release

      - name: Upload macOS binary to Cloudsmith
        if: matrix.os == 'macos-latest'
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw onismond/calc/macos/any-version target/release/calc
